language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
# command to run tests
script:
  - pylint --disable=R,C --rcfile=.pylintrc /py_ai_learn
  - python -m unittest discover